# Default values for ethereum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent

bootnode:
  replicaCount: 2
  image:
    repository: ethereum/client-go
    tag: alltools-stable

bootnodeRegistrar:
  replicaCount: 1
  image:
    repository: jpoon/bootnode-registrar
    tag: v1.0.0

ethstats:
  replicaCount: 1
  image:
    repository: ethereumex/eth-stats-dashboard
    tag: latest
  webSocketSecret: my-secret-for-connecting-to-ethstats
  service:
    type: LoadBalancer

geth:
  image:
    repository: ethereum/client-go
    tag: stable
  tx:
    # transaction nodes
    replicaCount: 2
    service:
      type: ClusterIP
  miner:
    # miner nodes
    replicaCount: 8
    account:
      secret: my-secret-account-password
  genesis:
    networkId: 98052
    accountsToFund:
      - da1e55471ded03adadee63ac658b671277a6c7d1
